services:
  # MySQL数据库
  mysql:
    image: mysql:5.7
    container_name: devops-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root123456
      MYSQL_DATABASE: message_db    # 必须和 app.py 里的数据库名一致
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - devops-network

  # Redis缓存
  redis:
    image: redis:alpine
    container_name: devops-redis
    restart: always
    volumes:
      - redis-data:/data
    networks:
      - devops-network

  # 后端Flask
  backend:
    build: ./backend
    container_name: devops-backend
    restart: always
    depends_on:
      - mysql
      - redis
    networks:
      - devops-network

  # Nginx代理
  nginx:
    build: ./nginx
    container_name: devops-nginx
    restart: always
    ports:
      - 80:80
    depends_on:
      - backend
    networks:
      - devops-network

volumes:
  mysql-data:
  redis-data:

networks:
  devops-network: